/**
 * setupTypes.js — single source of truth for setup type metadata.
 *
 * WHY THIS EXISTS:
 * setup_type is a plain string threaded through acd.js, setups.js, frontend components,
 * and backtest scripts. Each consumer used its own inline direction-inference heuristic
 * (includes('LONG'), endsWith('_SHORT'), etc.), creating silent contracts that broke
 * whenever a conditional variant type was added (e.g. WPP_FADE_SHORT_GAP_UP contains
 * "UP" but is a SHORT trade). This file makes those contracts explicit and executable.
 *
 * HOW TO USE:
 * - inferDirection(setupType) → 'LONG' | 'SHORT' | null
 *   Replace any inline includes('LONG')/endsWith('_SHORT') direction check with this.
 * - CONDITIONAL_VARIANTS — registry of types generated by resolveSetupType() in acd.js.
 *   test_invariants.mjs reads this to verify calibration pipeline coverage automatically.
 *
 * ADDING A NEW CONDITIONAL VARIANT:
 * 1. Add to resolveSetupType() in acd.js (the runtime override)
 * 2. Add an entry to CONDITIONAL_VARIANTS below (the registry)
 * 3. Run: node scripts/test_invariants.mjs  ← catches every other place automatically
 */

/**
 * STACK_VOL_BREAK_LIVE live detection thresholds — single source of truth so
 * computeStackVolSignal() (server/routes/acd.js) and /api/setups/reference (folded into
 * the "Misc" reference column's firing-gate tag, alongside every other setup_type's own
 * mechanisms — see computeMiscTags() in server/routes/setups.js) can never drift apart.
 * Added 2026-07-28 alongside the Setup Reference volZ column build — previously these
 * lived only as local consts inside computeStackVolSignal(), which is exactly the
 * hand-duplicated-threshold shape this file's own convention exists to prevent.
 */
export const STACK_VOL_THRESHOLDS = {
  RTH: { volZCutoff: 0.5, osrCutoff: 0.55, minClusterSize: 1 },
  GLOBEX: { volZCutoff: 1.5, osrCutoff: 0.65, minClusterSize: 2 },
};

/**
 * Infer trade direction from a setup type name.
 *
 * Algorithm:
 * 1. Strip conditional entry suffixes (_GAP_UP, _GAP_DOWN) — these describe how price
 *    arrived at the level, not which way the trade goes.
 *    e.g. WPP_FADE_SHORT_GAP_UP → WPP_FADE_SHORT → SHORT
 * 2. Match against direction keywords in the remaining name.
 *
 * Matches ALL 112 known setup types correctly. ZONE_EDGE_FADE returns null (no direction
 * in name) — treat null as "direction unknown" not "LONG".
 */
export const inferDirection = (setupType) => {
  if (!setupType) return null;
  const base = setupType.replace(/_GAP_(UP|DOWN)$/, '');
  if (base.includes('LONG') || base.includes('BULLISH') || base.includes('_UP')) return 'LONG';
  if (base.includes('SHORT') || base.includes('BEARISH') || base.includes('_DOWN')) return 'SHORT';
  // Standalone suffix check for types ending exactly in UP/DOWN without underscore prefix
  if (base.endsWith('UP')) return 'LONG';
  if (base.endsWith('DOWN')) return 'SHORT';
  return null;
};

/**
 * Extracted from server/routes/acd.js 2026-08-17 (OPEN_DECISION
 * islongsetup_bug_survives_in_3_other_files) so every consumer shares ONE direction
 * resolver instead of hand-rolling a copy — the exact "silent contract" failure mode
 * this file's own header comment exists to stop (a 4th independent copy in acd.js was
 * itself the fix for a 3-copy version of this same bug found earlier the same day).
 *
 * Combines inferDirection(setupType) (primary signal, correct for all 112 known-named
 * types, strips the _GAP_* suffix) with a general, setup-type-agnostic price-derived
 * fallback (row.t1_level > row.stop_level) for name-directionless types like
 * ZONE_EDGE_FADE — LONG trades have stop below entry and target above, SHORT the
 * reverse, and this sign is stable for a row's entire lifecycle (verified: none of this
 * codebase's `UPDATE active_setups` statements ever write stop_level/t1_level after
 * insert). A name/price DISAGREEMENT means the row's levels are inverted relative to
 * its name — returns null (exclude, don't guess) rather than trusting either signal.
 * Null/undefined stop_level or t1_level also returns null.
 */
export const resolveDirection = (row) => {
  if (row.stop_level == null || row.t1_level == null) return null;
  const named = inferDirection(row.setup_type);
  // Number()-coerced -- node-postgres returns NUMERIC columns (stop_level/t1_level's
  // real type) as JS strings by default. An uncoerced `>` here compares
  // lexicographically, which happens to agree with numeric order for this codebase's
  // current 5-digit uniform-precision index levels but is not correct in general.
  const t1 = Number(row.t1_level), stop = Number(row.stop_level);
  // Number.isFinite guard (DeepSeek code-review, 2026-08-17): a non-numeric string would
  // Number()-coerce to NaN, and `NaN > NaN` is false -- silently resolving to 'SHORT'
  // rather than null, violating this function's own "don't guess" contract. Unreachable
  // today (stop_level/t1_level are real NUMERIC columns), but cheap to guard properly.
  if (!Number.isFinite(t1) || !Number.isFinite(stop)) return null;
  const priceDerived = t1 > stop ? 'LONG' : 'SHORT';
  if (named !== null && named !== priceDerived) return null; // disagreement -- exclude
  return named ?? priceDerived;
};

/**
 * Registry of conditional variant setup types.
 *
 * A conditional variant is a type generated by resolveSetupType() in acd.js when the
 * base type name would fire but entry conditions differ enough to warrant separate
 * calibration. The base type is suppressed or fires normally; the variant is separate.
 *
 * test_invariants.mjs uses this to verify each variant has:
 * - SETUP_STATUS row in performance_audit
 * - OPTIMAL_STOP row in performance_audit
 * - inferDirection() returns the correct direction
 * - The backtest script exists on disk
 */
/**
 * Setup types whose direction is stored in the `direction` field of the active_setups row
 * at fire time, not encoded in the type name. inferDirection() correctly returns null for
 * these — that's expected, not a missing-suffix bug. test_invariants.mjs skips the null
 * warning for members of this set.
 */
export const CONTEXTUAL_DIRECTION_TYPES = new Set([
  'ZONE_EDGE_FADE', // direction = LONG/SHORT set at fire time based on zone position (ceiling vs floor)
]);

/**
 * Strategy family: MEAN_REVERSION (betting price reverts off a touched level) vs
 * CONTINUATION (betting price keeps moving the direction it's already moving).
 *
 * Built 2026-08-04 for docs/COMPRESSION_TAIL_MFE_SPEC.md Part 3, which requires every
 * setup_type be pre-registered into one of these two families BEFORE looking at any
 * tail-MFE result (the whole point: a real compression->expansion effect should plausibly
 * help CONTINUATION and hurt/neutral MEAN_REVERSION, so pooling both into one test would
 * let a true bidirectional effect cancel into apparent noise -- the same shape of dilution
 * that muted docs/REGIME_INTELLIGENCE_SPEC.md's Attempt 1 to $1.24/trade). Not a live
 * gating mechanism -- purely an analysis-time classification.
 *
 * Default rule: every '*_FADE_*' name (the large majority -- LEVEL_FADE_DEFINITIONS,
 * VWAP_MAGNET/GLOBEX_VWAP_MAGNET's own "mean-reversion ... back toward" criteria text,
 * ZONE_EDGE_FADE) is MEAN_REVERSION. Everything else is an explicit, individually-checked
 * override below -- verified against each setup's real detection criteria (acd.js
 * comments/descriptions, OTHER_SETUP_DEFINITIONS' criteria text, setups.js's
 * COUNTER_TREND_SETUPS set), not guessed from the name alone:
 *   - FAILED_AUCTION_*, STOP_SWEEP_*, GAP_FILL_*, OPEN_TEST_DRIVE_*: explicit "fade the
 *     failed breakout" / "now reversing" / gap-fill / open-rejection criteria text ->
 *     MEAN_REVERSION.
 *   - TRT_*, TRT_MAH_*, VALUE_AREA_RESPONSIVE_*: setups.js's own COUNTER_TREND_SETUPS set
 *     -> MEAN_REVERSION.
 *   - MOMENTUM_60m_60m_BALANCE_FADE (fades the move) -> MEAN_REVERSION;
 *     MOMENTUM_60m_60m_TREND ("trades with the move, not against it") -> CONTINUATION.
 *   - IB_BULLISH/IB_BEARISH (IB breaks and price closes beyond it), OPEN_DRIVE_*,
 *     BRACKET_BREAKOUT_*, STACK_VOL_BREAK_LIVE_* (spec's own examples), C_STANDALONE_*
 *     (targets an extension beyond OR high/low), A_UP_STRONG/A_DOWN_STRONG/A_UP_WEAK/
 *     A_DOWN_WEAK and C_PAIRED_* (all target a measured-move EXTENSION of an already-fired
 *     directional signal, per acd.js's t1GuardLabeled targets) -> CONTINUATION.
 * A setup_type absent from both the default rule and this override list returns null
 * (unclassified) rather than a silent guess -- callers must treat null as "needs
 * classifying before use," never default it to either family.
 */
const CONTINUATION_TYPES = new Set([
  'STACK_VOL_BREAK_LIVE_LONG', 'STACK_VOL_BREAK_LIVE_SHORT',
  'OPEN_DRIVE_LONG', 'OPEN_DRIVE_SHORT',
  'BRACKET_BREAKOUT_LONG', 'BRACKET_BREAKOUT_SHORT',
  'IB_BULLISH', 'IB_BEARISH',
  'MOMENTUM_60m_60m_TREND',
  'C_STANDALONE_UP', 'C_STANDALONE_DOWN',
  'A_UP_STRONG', 'A_DOWN_STRONG', 'A_UP_WEAK', 'A_DOWN_WEAK',
  'C_PAIRED_LONG', 'C_PAIRED_SHORT',
  // VWAP_RECLAIM_SHORT: docs/VWAP_RECLAIM_HOLD_SPEC.md's own description is explicit --
  // "a trend-continuation bet AWAY from VWAP, not a fade toward it." Found UNCLASSIFIED
  // 2026-08-10 (the only one of 181 real setup_types this mapping missed) while building
  // bet_class (roadmap I3) -- added here rather than left to fall through to UNCLASSIFIED.
  'VWAP_RECLAIM_SHORT',
  // RTH_FLUSH_*/GLOBEX_FLUSH_* (2026-08-27, docs/LIQUIDITY_ZONES_DEFENDED_LEVELS_SPEC.md
  // sec 4.4-4.14): enters in whichever direction a post-flush consolidation resolves --
  // a bet that the move CONTINUES in its resolved direction, not a fade of a touched level.
  // GLOBEX_FLUSH_REVERSAL_LONG/SHORT (added 2026-08-28) are deliberately NOT here -- see
  // MEAN_REVERSION_OVERRIDE_TYPES below, they trade the OPPOSITE of the departure direction
  // (a reversion back toward value), matching C_REVERSAL_LONG/SHORT's own classification.
  'RTH_FLUSH_LONG', 'RTH_FLUSH_SHORT', 'GLOBEX_FLUSH_LONG', 'GLOBEX_FLUSH_SHORT',
  // POC_ROTATION_JOIN_LONG/SHORT (2026-09-01, server/services/pocRotationJoinDetector.js):
  // JOIN = trade WITH the rotation leg's own direction once it converges back to the
  // running 24hr median fair value -- a bet the leg's move continues, not a fade of it.
  'POC_ROTATION_JOIN_LONG', 'POC_ROTATION_JOIN_SHORT',
]);
const MEAN_REVERSION_OVERRIDE_TYPES = new Set([
  'FAILED_AUCTION_LONG', 'FAILED_AUCTION_SHORT',
  'STOP_SWEEP_LONG', 'STOP_SWEEP_SHORT',
  'GAP_FILL_LONG', 'GAP_FILL_SHORT',
  'OPEN_TEST_DRIVE_LONG', 'OPEN_TEST_DRIVE_SHORT',
  'TRT_LONG', 'TRT_SHORT', 'TRT_LONG_V2', 'TRT_SHORT_V2',
  'TRT_MAH_LONG', 'TRT_MAH_SHORT',
  'VALUE_AREA_RESPONSIVE_LONG', 'VALUE_AREA_RESPONSIVE_SHORT',
  'VWAP_MAGNET_LONG', 'VWAP_MAGNET_SHORT',
  'GLOBEX_VWAP_MAGNET_LONG', 'GLOBEX_VWAP_MAGNET_SHORT',
  'MOMENTUM_60m_60m_BALANCE_FADE',
  'C_REVERSAL_LONG', 'C_REVERSAL_SHORT',
  // GLOBEX_FLUSH_REVERSAL_*: departure direction and resolution direction disagree -- price
  // leaves value one way, then reverts back through/toward it. A reversion bet, same shape as
  // C_REVERSAL_LONG/SHORT above, not a continuation of the original departure.
  'GLOBEX_FLUSH_REVERSAL_LONG', 'GLOBEX_FLUSH_REVERSAL_SHORT',
]);

export const inferStrategyFamily = (setupType) => {
  if (!setupType) return null;
  if (setupType.includes('_FADE') || MEAN_REVERSION_OVERRIDE_TYPES.has(setupType)) return 'MEAN_REVERSION';
  if (CONTINUATION_TYPES.has(setupType)) return 'CONTINUATION';
  return null;
};

/**
 * bet_class — roster-rebuild roadmap Phase 1, I3 (2026-08-10): "converts 130 fragmented
 * samples into one usable sample." Deliberately NOT a new classification built from
 * scratch — it's a thin rename/remap of the already-validated inferStrategyFamily()
 * above (built 2026-08-04, verified against each setup's real detection criteria, not
 * guessed from the name) onto the roadmap's own vocabulary:
 *   - MEAN_REVERSION -> 'VALUE_FADE' (the roadmap's own name for "Setup A — Value Fade
 *     (consolidation of the existing roster)", scratch/MASTER_OPUS_ROSTER_REBUILD_
 *     ROADMAP.md Part 3 — this IS the ~118-122-type fade roster the roadmap's Part 1.1
 *     diagnosis ("the roster is one bet wearing 130 costumes") is about.
 *   - CONTINUATION -> 'CONTINUATION_LEGACY', not 'CONTINUATION' bare and not folded into
 *     a future Setup C — these are pre-existing, already-live continuation-shaped bets
 *     (IB_BULLISH/BEARISH, OPEN_DRIVE, BRACKET_BREAKOUT, STACK_VOL_BREAK_LIVE,
 *     C_STANDALONE, A_UP/DOWN_STRONG/WEAK, C_PAIRED, MOMENTUM_60m_60m_TREND) that
 *     structurally are NOT part of the "130 costumes for one fade" problem (they're
 *     already a different bet), but they're also not one of the roadmap's new B-F
 *     setups (those don't exist yet) — a distinct, honest bucket, not a guess either way.
 *   - null (unclassified by inferStrategyFamily) -> 'UNCLASSIFIED'. Per the same
 *     "must be treated as needs-classifying, never defaulted" rule inferStrategyFamily's
 *     own docs state — a setup_type landing here needs a real classification decision,
 *     not a silent fold into VALUE_FADE or CONTINUATION_LEGACY.
 * Phase 1's own scope (this commit): the column + this mapping + an aggregation layer
 * (scripts/backtest_bet_class_status.mjs) that reports pooled real N/WR/EV per
 * bet_class. Deliberately NOT wired into the live stop/target lookup yet — the roadmap's
 * own Phase 2 checkpoint ("a defensible number for VALUE_FADE EV at an affordable stop,
 * from real data, with N in the hundreds") is a real resweep at consolidated N, not a
 * same-commit rewire of acd.js's live risk parameters. See OPEN_DECISION
 * bet_class_phase2_consolidated_resweep_not_started.
 */
// FAILED_SWEEP_REVERSAL_LONG/_SHORT (roadmap Phase 4, Setup B, 2026-08-11): a genuinely
// distinct bet from both buckets above -- entry is AFTER a level breaks (not a touch, so
// not MEAN_REVERSION in inferStrategyFamily()'s sense), but the trade itself fades BACK
// toward the level once it fails to hold (not a trend-continuation bet either). Deliberately
// its own bet_class rather than forced into the two-way inferStrategyFamily() split, per
// the roadmap's own Part 3 framing of Setup B as structurally distinct from Setup A.
const FAILED_SWEEP_REVERSAL_TYPES = new Set(['FAILED_SWEEP_REVERSAL_LONG', 'FAILED_SWEEP_REVERSAL_SHORT']);
// OPENING_DRIVE_15MIN_LONG/_SHORT (roadmap Phase 6, Setup D, 2026-08-11): deliberately a NEW
// setup_type, not a reuse of the pre-existing OPEN_DRIVE_LONG/SHORT (bet_class
// CONTINUATION_LEGACY, untouched, still 5min-OR-defined). Stage 1
// (scripts/backtest_setup_d_opening_drive_stage1.mjs) tested the CURRENT live 5-min-OR
// definition against a 15-min-OR-consistent variant with a required blind-delay confound
// control (per DeepSeek design critique): the 5-min (live) definition FAILED its own
// confound check (Arm A did not beat blind delay -- its apparent edge was indistinguishable
// from "just enter later"), while the 15-min variant passed cleanly (beats blind delay,
// beats a flat default, rigor-clean, N=138). Own bet_class rather than folded into
// CONTINUATION_LEGACY (reserved for the pre-existing, unvalidated OPEN_DRIVE_LONG/SHORT) or
// forced into inferStrategyFamily()'s two-way split, matching the FAILED_SWEEP_REVERSAL
// precedent immediately above -- each new roadmap Setup gets its own bet_class as it's built.
const OPENING_DRIVE_15MIN_TYPES = new Set(['OPENING_DRIVE_15MIN_LONG', 'OPENING_DRIVE_15MIN_SHORT']);
// GLOBEX_LEVEL (roadmap Phase 7, Setup F "Globex Level Test" consolidation, 2026-08-11):
// the overnight/Globex level-fade family (detectGlobexSetup(), server/routes/acd.js) --
// "overnight levels hold or reject during the low-liquidity session," structurally
// different from Setup A's RTH fades per the roadmap's own Part 3 framing (different
// liquidity, different participants, different session shape), so its own bet_class
// rather than folded into VALUE_FADE, matching the FAILED_SWEEP_REVERSAL/
// OPENING_DRIVE_15MIN precedent above.
//
// ONLY covers setup_type names that are UNAMBIGUOUSLY Globex-only by construction (the 4
// GLOBEX_-prefixed VWAP types, the 8 _OVERNIGHT-suffixed wider-window types -- see
// WIDER_WINDOW_OVERNIGHT_LEVELS in acd.js). Deliberately does NOT include
// PD_VAH_FADE_SHORT/PD_VAL_FADE_LONG/PD_POC_FADE_SHORT/PD_POC_FADE_LONG -- detectGlobexSetup()
// also fires these 4 under the SAME setup_type strings as their RTH siblings (a real,
// independently-found ambiguity: found live 2026-08-11 that getBetClass() was silently
// classifying every Globex fire of these 4 as VALUE_FADE, 300/304 historical rows across
// them). detectGlobexSetup()'s own INSERT now hardcodes bet_class='GLOBEX_LEVEL' directly
// for ALL its own inserts (it has ground truth -- every row it writes IS a Globex fire --
// so it doesn't need this function's name-based inference at all), which is why this Set
// doesn't need to solve the ambiguous-name case either: adding those 4 names here would
// make getBetClass() WRONG for their much-larger RTH-fired population instead. See
// OPEN_DECISION globex_ambiguous_names_need_session_backfill for the
// still-open question of correcting those 4 types' EXISTING historical rows.
const GLOBEX_LEVEL_TYPES = new Set([
  'GLOBEX_VWAP_MAGNET_LONG', 'GLOBEX_VWAP_MAGNET_SHORT',
  'GLOBEX_VWAP_FADE_LONG', 'GLOBEX_VWAP_FADE_SHORT',
  '3M_VAL_FADE_SHORT_OVERNIGHT', '3M_POC_FADE_SHORT_OVERNIGHT',
  'WS1_FADE_SHORT_OVERNIGHT', 'PM_POC_FADE_SHORT_OVERNIGHT',
  'MPP_FADE_SHORT_OVERNIGHT', 'MONTHLY_OPEN_FADE_LONG_OVERNIGHT',
  '10D_IB_MID_FADE_SHORT_OVERNIGHT', 'WR1_FADE_SHORT_OVERNIGHT',
]);
// IB_LOW_PNR_SHORT (2026-09-03, docs/EXTREME_PRESSURE_POINT_OF_NO_RETURN_SPEC.md): a
// genuinely new, freshly-validated continuation bet -- cumulative sell-side-delta
// z-score (90-day trailing, same-bar-index baseline, server/services/touchQuality.js's
// getCumulativeDeltaBaseline) crosses an extreme threshold while price is already below
// IB Low. NOT a fade (it bets AGAINST a reclaim, not for one) and NOT folded into
// CONTINUATION_LEGACY (reserved for pre-existing, already-live continuation bets,
// same reasoning as FAILED_SWEEP_REVERSAL/OPENING_DRIVE_15MIN above) -- own bet_class,
// own Set, matching that exact precedent. Deliberately does NOT use `_FADE` in its name
// (would silently misclassify via inferStrategyFamily as MEAN_REVERSION/VALUE_FADE, per
// DeepSeek design review). Upside (IB_HIGH, LONG) version failed rigor -- not built,
// this Set intentionally has only the SHORT side.
const IB_LOW_PNR_TYPES = new Set(['IB_LOW_PNR_SHORT']);
export const BET_CLASSES = ['VALUE_FADE', 'CONTINUATION_LEGACY', 'FAILED_SWEEP_REVERSAL', 'OPENING_DRIVE_15MIN', 'GLOBEX_LEVEL', 'IB_LOW_PNR', 'UNCLASSIFIED'];
export const getBetClass = (setupType) => {
  if (FAILED_SWEEP_REVERSAL_TYPES.has(setupType)) return 'FAILED_SWEEP_REVERSAL';
  if (OPENING_DRIVE_15MIN_TYPES.has(setupType)) return 'OPENING_DRIVE_15MIN';
  if (GLOBEX_LEVEL_TYPES.has(setupType)) return 'GLOBEX_LEVEL';
  if (IB_LOW_PNR_TYPES.has(setupType)) return 'IB_LOW_PNR';
  const family = inferStrategyFamily(setupType);
  if (family === 'MEAN_REVERSION') return 'VALUE_FADE';
  if (family === 'CONTINUATION') return 'CONTINUATION_LEGACY';
  return 'UNCLASSIFIED';
};

/**
 * Roster cap enforcement -- roadmap Phase 8, I7 (2026-08-11).
 * scratch/MASTER_OPUS_ROSTER_REBUILD_ROADMAP.md Part 4 I7 / Part 2 P2 / Part 9.
 *
 * "The roster is capped at 8 live types... Removing the cap requires an explicit registry
 * decision." "Code-level: attempting to set a ninth type to ACTIVE fails with a message
 * naming the eight current live types."
 *
 * WHAT "live" MEANS HERE, and why this isn't a simple runtime intercept -- design-critiqued
 * by DeepSeek before being written (scratch/deepseek_response.md, 2026-08-11): there is no
 * existing code path today that "promotes a bet_class to real capital." Every live-capital
 * decision in this codebase, before and after the rebuild, has been a human editing
 * SETUP_STATUS directly, per individual setup_type, via the pre-existing (untouched by this
 * rebuild) nightly ACTIVE/SUPPRESS pipeline -- there is no single choke point where "someone
 * just tried to activate a 9th type" can be intercepted yet, because "activate" isn't a
 * single function call anywhere in this system.
 *
 * So this enforces the cap at the level that DOES exist today -- the bet_class registry
 * itself -- via two real, currently-running mechanisms:
 *   1. assertRosterCapNotExceeded(), called at THIS MODULE'S LOAD TIME (a startup guard,
 *      not a live-editing watcher -- DeepSeek correctly flagged that Node's ESM cache means
 *      editing this file on a running process does NOT re-trigger this check; it fires on
 *      the next process start, which for the systemd-managed server means "the service
 *      fails to start" if BET_CLASS_STAGE is ever edited to add a 9th LEGACY_LIVE/
 *      STAGE_4_ACTIVE entry -- a real, load-bearing guard, just not a filesystem watcher).
 *   2. scripts/test_invariants.mjs check [18] re-validates the same cap + BET_CLASS_STAGE/
 *      BET_CLASSES sync on every routine self-check run, so a bad registry edit is caught
 *      long before it ever reaches a deploy/restart.
 * promoteBetClassStage() is exported as the SINGLE INTENDED FUTURE CHOKE POINT for whenever
 * this system's first genuine Stage 4 promotion happens (none has, as of this build -- every
 * currently-LEGACY_LIVE bet_class predates this rebuild, and FAILED_SWEEP_REVERSAL/
 * OPENING_DRIVE_15MIN are both still SHADOW). It is unused today -- that is expected, not a
 * bug -- but per DeepSeek's review, a real Stage 4 promotion will need to coordinate more
 * than this one cap check (updating whichever setup_types make up that bet_class in
 * SETUP_STATUS, logging the decision, writing a RESEARCH_CLAIM) -- this function is the
 * placeholder for that future coordination point, not the whole of it. Do not wire a future
 * promotion script directly to a database write that bypasses this function.
 *
 * LEGACY COUNTS TOWARD THE CAP: VALUE_FADE, CONTINUATION_LEGACY, GLOBEX_LEVEL are pre-
 * existing, already-live-at-real-capital bet_classes (the individual setup_types beneath
 * them have fired live money since before this rebuild started) -- they occupy 3 of the 8
 * slots. This matches the roadmap's own Part 9 target state ("6-8 live types" twelve months
 * out, explicitly including Setups A and F, which ARE these legacy consolidations) and was
 * confirmed against that reading by DeepSeek's review before this was written.
 *
 * WORTH RECORDING (not a code concern, a roadmap-tracking one): with Setups C and E killed
 * by Phase 5's failed TREND/TURBULENT discriminator, the maximum realistic near-term live
 * bet_class count from the roadmap's original 6 setups is 4 (A, B, D, F) plus the pre-
 * existing CONTINUATION_LEGACY bucket = 5, or 6 if a future new bet_class emerges -- below
 * Part 9's own "6-8" target range. The cap of 8 is NOT the binding constraint on this
 * system reaching that range; Phase 5's negative result is. Do not read "roster cap not yet
 * hit" as "the roadmap is on track for 6-8" -- those are two different questions.
 */
export const ROSTER_CAP = 8;

// 'LEGACY_LIVE' = pre-existing, already trading real capital via the untouched SETUP_STATUS
// pipeline (predates this rebuild). 'SHADOW' = roadmap-built, no real capital yet. A future
// genuine Stage 4 promotion should read 'STAGE_4_ACTIVE' -- no bet_class has reached that
// state as of this build. UNCLASSIFIED is deliberately absent -- it can never be "live" as
// its own bet (it is the catch-all for setup_types nobody has classified yet).
export const BET_CLASS_STAGE = {
  VALUE_FADE: 'LEGACY_LIVE',
  CONTINUATION_LEGACY: 'LEGACY_LIVE',
  GLOBEX_LEVEL: 'LEGACY_LIVE',
  FAILED_SWEEP_REVERSAL: 'SHADOW',
  OPENING_DRIVE_15MIN: 'SHADOW',
  IB_LOW_PNR: 'SHADOW',
};

const LIVE_STAGES = new Set(['LEGACY_LIVE', 'STAGE_4_ACTIVE']);

// Real function, not decoration -- called at the bottom of this file (module load time).
// Throws (not just logs) so an invalid registry can never be silently imported by any
// consumer; a thrown error at import time takes the whole process down at startup rather
// than letting a bad cap slip into a running server.
export function assertRosterCapNotExceeded(stageMap = BET_CLASS_STAGE) {
  const liveClasses = Object.entries(stageMap)
    .filter(([, stage]) => LIVE_STAGES.has(stage))
    .map(([betClass]) => betClass);
  if (liveClasses.length > ROSTER_CAP) {
    throw new Error(
      `Roster cap exceeded: ${liveClasses.length} live bet_classes (cap=${ROSTER_CAP}) -- ` +
      `current live set: ${liveClasses.join(', ')}. Adding a live bet_class beyond the cap ` +
      `requires an explicit registry decision (roadmap Part 2 P2), not a routine edit.`
    );
  }
  return liveClasses;
}

/**
 * The single intended future choke point for promoting a bet_class to real capital
 * (roadmap Stage 4). UNUSED as of this build -- no bet_class has reached Stage 4 yet. See
 * the header comment above for what a real promotion will additionally need to coordinate
 * (SETUP_STATUS updates for the constituent setup_types, a performance_audit/RESEARCH_CLAIM
 * record of the decision) beyond the cap check this function performs today.
 */
export function promoteBetClassStage(betClass, newStage) {
  if (!BET_CLASSES.includes(betClass)) {
    throw new Error(`promoteBetClassStage: '${betClass}' is not a known bet_class (see BET_CLASSES)`);
  }
  const nextStageMap = { ...BET_CLASS_STAGE, [betClass]: newStage };
  assertRosterCapNotExceeded(nextStageMap); // throws before mutating anything if this would exceed the cap
  BET_CLASS_STAGE[betClass] = newStage;
  return BET_CLASS_STAGE;
}

// Startup guard (see header comment) -- runs once, at module load, in every process that
// imports this file (server/index.js, every backtest/calibration script, test_invariants.mjs).
assertRosterCapNotExceeded();

export const CONDITIONAL_VARIANTS = {
  WPP_FADE_SHORT_GAP_UP: {
    baseType: 'WPP_FADE_SHORT',
    direction: 'SHORT',
    condition: 'session 9:30 open is BELOW WPP (gap brought price up into resistance)',
    backtestScript: 'scripts/backtest_wpp_short_gap.mjs',
    addedDate: '2026-07-09',
    monitorAtN: 50,
    // conditional_variant_setup_status_daily_overwrite_race (OPEN_DECISION, found 2026-08-03):
    // backtest_wpp_short_gap.mjs's own population is filtered by `open_below_wpp` — a real
    // ENTRY condition the generic backtest_setup_status.mjs (a blind `GROUP BY setup_type`
    // scan) can't replicate. That script is weekly-only, but the generic script runs daily
    // and writes the SAME signal_type='SETUP_STATUS' row for this exact signal_name off its
    // own (wrong, unfiltered) population — confirmed live 2026-08-10: correctly ACTIVE/N=30
    // from Sunday's dedicated run, silently overwritten to THIN_N/N=1 by Monday morning's
    // generic run, every single weekday. This flag tells backtest_setup_status.mjs to skip
    // writing SETUP_STATUS for this signal_name entirely, leaving it fully to the dedicated
    // script — a several-days-stale CORRECT row (still within the 8-day freshness window the
    // session-start coverage check uses) beats a fresh WRONG one every time. Do NOT set this
    // on the _TRAIL variants below — their dedicated script (backtest_breakeven_trail.mjs)
    // writes to signal_type='BREAKEVEN_TRAIL_TEST', not SETUP_STATUS, so there's no competing
    // writer and the generic script's own SETUP_STATUS evaluation for them is correct/needed.
    skipGenericSetupStatus: true,
  },
  OR5_LOW_FADE_LONG_GAP_DOWN: {
    baseType: 'OR5_LOW_FADE_LONG',
    direction: 'LONG',
    condition: 'session 9:30 open is BELOW the prior session\'s RTH close (gap brought price down into the OR5 low, a support fade)',
    backtestScript: 'scripts/backtest_or5_low_gap_down.mjs',
    addedDate: '2026-08-18',
    monitorAtN: 50,
    // Same overwrite-race reasoning as WPP_FADE_SHORT_GAP_UP above: the generic weekly
    // scan can't replicate the gap-down entry filter, so it would silently overwrite
    // this variant's correct row with a wrong unfiltered one.
    skipGenericSetupStatus: true,
    // DELIBERATE DEVIATION from the WPP precedent: backtest_or5_low_gap_down.mjs hardcodes
    // recommendation='THIN_N' regardless of its own backtest N/EV (N=147, EV=$7.77 as of
    // 2026-08-18) rather than letting the threshold compute ACTIVE. WPP_FADE_SHORT_GAP_UP's
    // script DOES let the threshold compute ACTIVE, and that variant is currently live
    // ACTIVE with ZERO real origin_status='ACTIVE' trades ever -- flagged as an open
    // INVARIANT_WARN, not a pattern to replicate. This variant stays SHADOW-only until real
    // forward trades (origin_status IN ('ACTIVE','SHADOW')) reach N>=20 with acceptable EV,
    // and promotion to ACTIVE must be a deliberate manual step, not automatic. See
    // backtest_or5_low_gap_down.mjs's file header and docs/OPEN_THREADS.md 2026-08-18.
    forcedShadowPendingRealValidation: true,
  },
  // Not entry-conditional like the variant above — every FLOOR_R1_FADE_SHORT touch is
  // unconditionally diverted here, because the thing that differs is the EXIT mechanism
  // (breakeven-then-trail instead of a fixed single target), not the entry. Kept in this
  // registry anyway per docs/SCALEOUT_RUNNER_SPEC.md §4: mixing the new mechanism's EV
  // distribution into the base type's own live calibration would be a real distortion,
  // so it gets its own name and its own SETUP_STATUS lifecycle. `trailSignalName` is the
  // performance_audit BREAKEVEN_TRAIL_TEST signal_name to read runner_trail_width from
  // (server/routes/acd.js reads this at insert time — never hardcode the trail width
  // itself). First of 6 backtested survivors to be wired live (largest N); the other 5
  // (docs/SCALEOUT_RUNNER_SPEC.md §2 table) are deliberately not yet built — add them the
  // same way, one at a time, once this one proves itself at live N>=20.
  FLOOR_R1_FADE_SHORT_TRAIL: {
    baseType: 'FLOOR_R1_FADE_SHORT',
    direction: 'SHORT',
    condition: 'unconditional — every FLOOR_R1_FADE_SHORT touch (exit mechanism changes, not entry)',
    backtestScript: 'scripts/backtest_breakeven_trail.mjs',
    trailSignalName: 'A_FLOOR_R1_FADE_SHORT',
    addedDate: '2026-07-19',
    monitorAtN: 20,
  },
  // The other 5 of 6 backtested breakeven-trail survivors (docs/SCALEOUT_RUNNER_SPEC.md
  // §2 table), wired 2026-07-21 following the exact FLOOR_R1_FADE_SHORT_TRAIL pattern
  // above. Caveat found before wiring these: FLOOR_R1_FADE_SHORT_TRAIL itself has had
  // ZERO real (non-suppressed) live touches since 2026-07-19 -- its own gating condition
  // ("prove itself at live N>=20" before adding more) was not actually met. Wired anyway
  // per explicit user direction, SHADOW-only (no live capital risk either way) -- but
  // this means none of the 6 has real forward validation yet, only the backtest.
  PW_HIGH_FADE_LONG_TRAIL: {
    baseType: 'PW_HIGH_FADE_LONG',
    direction: 'LONG',
    condition: 'unconditional — every PW_HIGH_FADE_LONG touch (exit mechanism changes, not entry)',
    backtestScript: 'scripts/backtest_breakeven_trail.mjs',
    trailSignalName: 'B_PW_HIGH_FADE_LONG',
    addedDate: '2026-07-21',
    monitorAtN: 20,
  },
  PD_POC_FADE_LONG_TRAIL: {
    baseType: 'PD_POC_FADE_LONG',
    direction: 'LONG',
    condition: 'unconditional — every PD_POC_FADE_LONG touch (exit mechanism changes, not entry)',
    backtestScript: 'scripts/backtest_breakeven_trail.mjs',
    trailSignalName: 'B_PD_POC_FADE_LONG',
    addedDate: '2026-07-21',
    monitorAtN: 20,
  },
  FLOOR_S1_FADE_LONG_TRAIL: {
    baseType: 'FLOOR_S1_FADE_LONG',
    direction: 'LONG',
    condition: 'unconditional — every FLOOR_S1_FADE_LONG touch (exit mechanism changes, not entry)',
    backtestScript: 'scripts/backtest_breakeven_trail.mjs',
    trailSignalName: 'B_FLOOR_S1_FADE_LONG',
    addedDate: '2026-07-21',
    monitorAtN: 20,
  },
  DAILY_OPEN_FADE_LONG_TRAIL: {
    baseType: 'DAILY_OPEN_FADE_LONG',
    direction: 'LONG',
    condition: 'unconditional — every DAILY_OPEN_FADE_LONG touch (exit mechanism changes, not entry)',
    backtestScript: 'scripts/backtest_breakeven_trail.mjs',
    trailSignalName: 'B_DAILY_OPEN_FADE_LONG',
    addedDate: '2026-07-21',
    monitorAtN: 20,
  },
  CAM_S2_FADE_LONG_TRAIL: {
    baseType: 'CAM_S2_FADE_LONG',
    direction: 'LONG',
    condition: 'unconditional — every CAM_S2_FADE_LONG touch (exit mechanism changes, not entry)',
    backtestScript: 'scripts/backtest_breakeven_trail.mjs',
    trailSignalName: 'B_CAM_S2_FADE_LONG',
    addedDate: '2026-07-21',
    monitorAtN: 20,
  },
  // 7th trail variant (2026-08-26) -- the original 6 above were picked by an earlier
  // backtest but never accumulated enough real live touches (0-18 of the required 20) to
  // pass this mechanism's own MIN_N floor; confirmed none of them has ever produced a
  // fresh BREAKEVEN_TRAIL_TEST row from real data. Found by re-scanning every currently
  // real-eligible setup_type (12 clear MIN_N=20) against the actual trail-validation
  // funnel: PD_POC_FADE_SHORT is the only survivor (real N=21, Tier B, trail=19.3pt,
  // OOS EV +$30.31 vs a -$2.31 OOS fixed-target baseline). High-frequency real setups
  // (IB_BEARISH real_n=147, IB_BULLISH real_n=68) were also tested and genuinely fail the
  // OOS/plateau guardrails -- not a data-volume problem, a real distribution-shape one.
  PD_POC_FADE_SHORT_TRAIL: {
    baseType: 'PD_POC_FADE_SHORT',
    direction: 'SHORT',
    condition: 'unconditional — every PD_POC_FADE_SHORT touch (exit mechanism changes, not entry)',
    backtestScript: 'scripts/backtest_breakeven_trail.mjs',
    trailSignalName: 'B_PD_POC_FADE_SHORT',
    addedDate: '2026-08-26',
    monitorAtN: 20,
  },
};

/**
 * Legacy hardcoded fallback for setup_types that don't yet have a SETUP_STATUS row at all
 * (server/routes/acd.js's getShadowSetupTypes() only knows about types WITH a row --
 * a query can't distinguish "confirmed fine to show" from "never assessed"). Hides
 * brand-new/experimental types from the default Setup Log view until their first real
 * calibration run.
 *
 * PRUNED 2026-07-17: this list previously had 27 entries; querying SETUP_STATUS directly
 * showed 22 of them already had real rows (all correctly SUPPRESS/THIN_N today, so no
 * visible bug yet) -- meaning the list had quietly become 81% dead weight, AND a live
 * landmine: several of the redundant entries are THIN_N purely on small sample size with
 * positive EV (e.g. C_PAIRED_SHORT N=6 EV=+$320, A_DOWN_WEAK N=5 EV=+$208.60) -- if any
 * earns enough trades to hit PROMOTE later, this hardcoded list would keep hiding it
 * forever, the exact same staleness bug SHADOW_SETUP_TYPES was replaced for. Pruned to
 * only the 5 types confirmed to have zero SETUP_STATUS row at prune time.
 *
 * scripts/test_invariants.mjs check [6] re-verifies every entry here against live
 * SETUP_STATUS on each run and fails if one has picked up a real row -- so this can't
 * silently drift stale again the way the pruned version did. When that check fails,
 * remove the flagged entry from this Set; do not just silence the check.
 */
export const UNCALIBRATED_SHADOW_TYPES = new Set([
  'GAP_FILL_LONG', 'A_UP_WEAK', 'A_DOWN_STRONG',
]);

/**
 * classifyLevelFormation() — 2026-08-30, born from the volume-building-strength research thread
 * (docs/VOLUME_BUILDING_EXPANSION_SIGNAL_SPEC.md). Distinguishes SAME_DAY_FORMING levels
 * (Initial Balance / Opening Range, any length — established fresh THIS session) from
 * PRIOR_DAY_OR_DEVELOPING levels (fixed from a completed prior period, or a slowly-accumulating
 * running average — floor pivots, camarilla, prior-day/week/year value areas, VWAP variants,
 * overnight high/low, session-open references). A different axis from inferStrategyFamily()
 * above (MEAN_REVERSION/CONTINUATION) and from getBetClass() (roadmap bet-class buckets) — this
 * one is specifically about WHEN a level came into existence relative to the current session, not
 * what kind of trade it produces.
 *
 * Found to matter a lot: RESEARCH_CLAIM momentum_ctx_sameday_effect_sharpened_full_reclassify —
 * whether a fade's approach showed real recent volume/pace activity predicts fade outcome ~5.5x
 * more strongly for SAME_DAY_FORMING levels ($11.95/trade gap, N=324) than for
 * PRIOR_DAY_OR_DEVELOPING ones ($2.17/trade, N=618). First version of this classifier lived only
 * as copy-pasted regex in throwaway scratch scripts and had a real gap (missed OR*_HIGH/LOW,
 * only caught OR*_MID) that diluted the true-OTHER residual with 90% avoidable noise — promoted
 * here so no future script re-derives (and potentially re-drifts) this by hand.
 */
// CORRECTED 2026-08-30 (DeepSeek code review, same day as the original build): the first version
// was hand-rolled regex against setup_type name patterns and got it wrong on 54 of 168 live FADE
// setup_types -- worst, it put 13 real PRIOR_PERIOD setup_types (PD_IB_HIGH/LOW/MID, PD_OR_MID,
// 5D_OR_MID, 10D_IB_MID -- all literally "PD_" for Prior Day) INTO SAME_DAY_FORMING, contaminating
// ~15% of the headline research bucket with the wrong population. Worse: this duplicated an axis
// that already existed as a real, authoritative table -- setupDefinitions.js's own
// LEVEL_FADE_DEFINITIONS[].rule field (SAME_DAY_FORMING/PRIOR_PERIOD/...), built 2026-07-20
// specifically to be "the single source of truth... keyed by the same base level names already
// used in server/config/setupTypes.js." Skipping that check violated this codebase's own "check
// whether an existing column/function already answers this" rule. Fixed by projecting off that
// table instead of re-deriving the classification by hand.
import { LEVEL_FADE_DEFINITIONS, stripToBaseLevel } from './setupDefinitions.js';

export const classifyLevelFormation = (setupType) => {
  if (!setupType) return 'OTHER';
  const base = stripToBaseLevel(setupType);
  const rule = LEVEL_FADE_DEFINITIONS[base]?.rule;
  if (rule === 'SAME_DAY_FORMING') return 'SAME_DAY_FORMING';
  if (rule === 'PRIOR_PERIOD') return 'PRIOR_DAY_OR_DEVELOPING';
  return 'OTHER'; // MOMENTUM_PATTERN, OVERNIGHT_RANGE, DAY_TYPE_CONDITIONAL, or no definition at all
};

// Added 2026-08-31 (OPEN_DECISION globex_trail_diversion_never_applied_20260831, user-confirmed
// "add trail diversion to Globex too"). server/routes/acd.js's RTH engine has its own local
// resolveSetupType() closure (~line 7285) that hand-lists the 7 UNCONDITIONAL trail-diversion
// base types (every touch of that type gets the breakeven-trail mechanism, no entry-condition
// check) inline, duplicating exactly what CONDITIONAL_VARIANTS already encodes via each entry's
// own `baseType` field and `condition: 'unconditional...'` string. detectGlobexSetup() needed
// the SAME unconditional-only mapping (it has no access to the RTH closure's scope -- allRthBarsRow/
// lp aren't available there, and those are only needed by resolveSetupType()'s two CONDITIONAL
// entries, WPP_FADE_SHORT/OR5_LOW_FADE_LONG, which are RTH-Opening-Range-specific and don't apply
// to Globex anyway) -- rather than hand-copying the same 7-line if-chain a second time (the
// original sin this whole OPEN_DECISION traces back to), this derives the mapping FROM
// CONDITIONAL_VARIANTS directly, so there is exactly one place a new unconditional trail variant
// ever needs to be added. Deliberately does NOT touch the RTH resolveSetupType() closure itself
// (lower-risk additive change; that function's own conditional entries are out of scope here).
const UNCONDITIONAL_VARIANT_BY_BASE_TYPE = (() => {
  const map = {};
  for (const [variantName, v] of Object.entries(CONDITIONAL_VARIANTS)) {
    if (v.baseType && typeof v.condition === 'string' && v.condition.startsWith('unconditional')) {
      map[v.baseType] = variantName;
    }
  }
  return map;
})();

/**
 * Given a RAW (undiverted) setup_type, returns its unconditional trail-diversion variant name
 * (e.g. 'PD_POC_FADE_LONG' -> 'PD_POC_FADE_LONG_TRAIL') if one exists in CONDITIONAL_VARIANTS,
 * else returns the input unchanged. Only covers UNCONDITIONAL diversions (every touch of the
 * base type diverts, no entry-condition check) -- the RTH-only conditional diversions
 * (WPP_FADE_SHORT_GAP_UP, OR5_LOW_FADE_LONG_GAP_DOWN) are NOT handled here, since they depend on
 * RTH-specific same-session data (today's opening range) that has no Globex/overnight analog.
 */
export function resolveUnconditionalTrailVariant(rawType) {
  return UNCONDITIONAL_VARIANT_BY_BASE_TYPE[rawType] ?? rawType;
}
