/**
 * setupTypes.js — single source of truth for setup type metadata.
 *
 * WHY THIS EXISTS:
 * setup_type is a plain string threaded through acd.js, setups.js, frontend components,
 * and backtest scripts. Each consumer used its own inline direction-inference heuristic
 * (includes('LONG'), endsWith('_SHORT'), etc.), creating silent contracts that broke
 * whenever a conditional variant type was added (e.g. WPP_FADE_SHORT_GAP_UP contains
 * "UP" but is a SHORT trade). This file makes those contracts explicit and executable.
 *
 * HOW TO USE:
 * - inferDirection(setupType) → 'LONG' | 'SHORT' | null
 *   Replace any inline includes('LONG')/endsWith('_SHORT') direction check with this.
 * - CONDITIONAL_VARIANTS — registry of types generated by resolveSetupType() in acd.js.
 *   test_invariants.mjs reads this to verify calibration pipeline coverage automatically.
 *
 * ADDING A NEW CONDITIONAL VARIANT:
 * 1. Add to resolveSetupType() in acd.js (the runtime override)
 * 2. Add an entry to CONDITIONAL_VARIANTS below (the registry)
 * 3. Run: node scripts/test_invariants.mjs  ← catches every other place automatically
 */

/**
 * Infer trade direction from a setup type name.
 *
 * Algorithm:
 * 1. Strip conditional entry suffixes (_GAP_UP, _GAP_DOWN) — these describe how price
 *    arrived at the level, not which way the trade goes.
 *    e.g. WPP_FADE_SHORT_GAP_UP → WPP_FADE_SHORT → SHORT
 * 2. Match against direction keywords in the remaining name.
 *
 * Matches ALL 112 known setup types correctly. ZONE_EDGE_FADE returns null (no direction
 * in name) — treat null as "direction unknown" not "LONG".
 */
export const inferDirection = (setupType) => {
  if (!setupType) return null;
  const base = setupType.replace(/_GAP_(UP|DOWN)$/, '');
  if (base.includes('LONG') || base.includes('BULLISH') || base.includes('_UP')) return 'LONG';
  if (base.includes('SHORT') || base.includes('BEARISH') || base.includes('_DOWN')) return 'SHORT';
  // Standalone suffix check for types ending exactly in UP/DOWN without underscore prefix
  if (base.endsWith('UP')) return 'LONG';
  if (base.endsWith('DOWN')) return 'SHORT';
  return null;
};

/**
 * Registry of conditional variant setup types.
 *
 * A conditional variant is a type generated by resolveSetupType() in acd.js when the
 * base type name would fire but entry conditions differ enough to warrant separate
 * calibration. The base type is suppressed or fires normally; the variant is separate.
 *
 * test_invariants.mjs uses this to verify each variant has:
 * - SETUP_STATUS row in performance_audit
 * - OPTIMAL_STOP row in performance_audit
 * - inferDirection() returns the correct direction
 * - The backtest script exists on disk
 */
/**
 * Setup types whose direction is stored in the `direction` field of the active_setups row
 * at fire time, not encoded in the type name. inferDirection() correctly returns null for
 * these — that's expected, not a missing-suffix bug. test_invariants.mjs skips the null
 * warning for members of this set.
 */
export const CONTEXTUAL_DIRECTION_TYPES = new Set([
  'ZONE_EDGE_FADE', // direction = LONG/SHORT set at fire time based on zone position (ceiling vs floor)
]);

export const CONDITIONAL_VARIANTS = {
  WPP_FADE_SHORT_GAP_UP: {
    baseType: 'WPP_FADE_SHORT',
    direction: 'SHORT',
    condition: 'session 9:30 open is BELOW WPP (gap brought price up into resistance)',
    backtestScript: 'scripts/backtest_wpp_short_gap.mjs',
    addedDate: '2026-07-09',
    monitorAtN: 50,
  },
};
