/**
 * setupTypes.js — single source of truth for setup type metadata.
 *
 * WHY THIS EXISTS:
 * setup_type is a plain string threaded through acd.js, setups.js, frontend components,
 * and backtest scripts. Each consumer used its own inline direction-inference heuristic
 * (includes('LONG'), endsWith('_SHORT'), etc.), creating silent contracts that broke
 * whenever a conditional variant type was added (e.g. WPP_FADE_SHORT_GAP_UP contains
 * "UP" but is a SHORT trade). This file makes those contracts explicit and executable.
 *
 * HOW TO USE:
 * - inferDirection(setupType) → 'LONG' | 'SHORT' | null
 *   Replace any inline includes('LONG')/endsWith('_SHORT') direction check with this.
 * - CONDITIONAL_VARIANTS — registry of types generated by resolveSetupType() in acd.js.
 *   test_invariants.mjs reads this to verify calibration pipeline coverage automatically.
 *
 * ADDING A NEW CONDITIONAL VARIANT:
 * 1. Add to resolveSetupType() in acd.js (the runtime override)
 * 2. Add an entry to CONDITIONAL_VARIANTS below (the registry)
 * 3. Run: node scripts/test_invariants.mjs  ← catches every other place automatically
 */

/**
 * STACK_VOL_BREAK_LIVE live detection thresholds — single source of truth so
 * computeStackVolSignal() (server/routes/acd.js) and /api/setups/reference (which
 * displays these as the "Applied volZ" reference column) can never drift apart.
 * Added 2026-07-28 alongside the Setup Reference volZ column build — previously these
 * lived only as local consts inside computeStackVolSignal(), which is exactly the
 * hand-duplicated-threshold shape this file's own convention exists to prevent.
 */
export const STACK_VOL_THRESHOLDS = {
  RTH: { volZCutoff: 0.5, osrCutoff: 0.55, minClusterSize: 1 },
  GLOBEX: { volZCutoff: 1.5, osrCutoff: 0.65, minClusterSize: 2 },
};

/**
 * Infer trade direction from a setup type name.
 *
 * Algorithm:
 * 1. Strip conditional entry suffixes (_GAP_UP, _GAP_DOWN) — these describe how price
 *    arrived at the level, not which way the trade goes.
 *    e.g. WPP_FADE_SHORT_GAP_UP → WPP_FADE_SHORT → SHORT
 * 2. Match against direction keywords in the remaining name.
 *
 * Matches ALL 112 known setup types correctly. ZONE_EDGE_FADE returns null (no direction
 * in name) — treat null as "direction unknown" not "LONG".
 */
export const inferDirection = (setupType) => {
  if (!setupType) return null;
  const base = setupType.replace(/_GAP_(UP|DOWN)$/, '');
  if (base.includes('LONG') || base.includes('BULLISH') || base.includes('_UP')) return 'LONG';
  if (base.includes('SHORT') || base.includes('BEARISH') || base.includes('_DOWN')) return 'SHORT';
  // Standalone suffix check for types ending exactly in UP/DOWN without underscore prefix
  if (base.endsWith('UP')) return 'LONG';
  if (base.endsWith('DOWN')) return 'SHORT';
  return null;
};

/**
 * Registry of conditional variant setup types.
 *
 * A conditional variant is a type generated by resolveSetupType() in acd.js when the
 * base type name would fire but entry conditions differ enough to warrant separate
 * calibration. The base type is suppressed or fires normally; the variant is separate.
 *
 * test_invariants.mjs uses this to verify each variant has:
 * - SETUP_STATUS row in performance_audit
 * - OPTIMAL_STOP row in performance_audit
 * - inferDirection() returns the correct direction
 * - The backtest script exists on disk
 */
/**
 * Setup types whose direction is stored in the `direction` field of the active_setups row
 * at fire time, not encoded in the type name. inferDirection() correctly returns null for
 * these — that's expected, not a missing-suffix bug. test_invariants.mjs skips the null
 * warning for members of this set.
 */
export const CONTEXTUAL_DIRECTION_TYPES = new Set([
  'ZONE_EDGE_FADE', // direction = LONG/SHORT set at fire time based on zone position (ceiling vs floor)
]);

export const CONDITIONAL_VARIANTS = {
  WPP_FADE_SHORT_GAP_UP: {
    baseType: 'WPP_FADE_SHORT',
    direction: 'SHORT',
    condition: 'session 9:30 open is BELOW WPP (gap brought price up into resistance)',
    backtestScript: 'scripts/backtest_wpp_short_gap.mjs',
    addedDate: '2026-07-09',
    monitorAtN: 50,
  },
  // Not entry-conditional like the variant above — every FLOOR_R1_FADE_SHORT touch is
  // unconditionally diverted here, because the thing that differs is the EXIT mechanism
  // (breakeven-then-trail instead of a fixed single target), not the entry. Kept in this
  // registry anyway per docs/SCALEOUT_RUNNER_SPEC.md §4: mixing the new mechanism's EV
  // distribution into the base type's own live calibration would be a real distortion,
  // so it gets its own name and its own SETUP_STATUS lifecycle. `trailSignalName` is the
  // performance_audit BREAKEVEN_TRAIL_TEST signal_name to read runner_trail_width from
  // (server/routes/acd.js reads this at insert time — never hardcode the trail width
  // itself). First of 6 backtested survivors to be wired live (largest N); the other 5
  // (docs/SCALEOUT_RUNNER_SPEC.md §2 table) are deliberately not yet built — add them the
  // same way, one at a time, once this one proves itself at live N>=20.
  FLOOR_R1_FADE_SHORT_TRAIL: {
    baseType: 'FLOOR_R1_FADE_SHORT',
    direction: 'SHORT',
    condition: 'unconditional — every FLOOR_R1_FADE_SHORT touch (exit mechanism changes, not entry)',
    backtestScript: 'scripts/backtest_breakeven_trail.mjs',
    trailSignalName: 'A_FLOOR_R1_FADE_SHORT',
    addedDate: '2026-07-19',
    monitorAtN: 20,
  },
  // The other 5 of 6 backtested breakeven-trail survivors (docs/SCALEOUT_RUNNER_SPEC.md
  // §2 table), wired 2026-07-21 following the exact FLOOR_R1_FADE_SHORT_TRAIL pattern
  // above. Caveat found before wiring these: FLOOR_R1_FADE_SHORT_TRAIL itself has had
  // ZERO real (non-suppressed) live touches since 2026-07-19 -- its own gating condition
  // ("prove itself at live N>=20" before adding more) was not actually met. Wired anyway
  // per explicit user direction, SHADOW-only (no live capital risk either way) -- but
  // this means none of the 6 has real forward validation yet, only the backtest.
  PW_HIGH_FADE_LONG_TRAIL: {
    baseType: 'PW_HIGH_FADE_LONG',
    direction: 'LONG',
    condition: 'unconditional — every PW_HIGH_FADE_LONG touch (exit mechanism changes, not entry)',
    backtestScript: 'scripts/backtest_breakeven_trail.mjs',
    trailSignalName: 'B_PW_HIGH_FADE_LONG',
    addedDate: '2026-07-21',
    monitorAtN: 20,
  },
  PD_POC_FADE_LONG_TRAIL: {
    baseType: 'PD_POC_FADE_LONG',
    direction: 'LONG',
    condition: 'unconditional — every PD_POC_FADE_LONG touch (exit mechanism changes, not entry)',
    backtestScript: 'scripts/backtest_breakeven_trail.mjs',
    trailSignalName: 'B_PD_POC_FADE_LONG',
    addedDate: '2026-07-21',
    monitorAtN: 20,
  },
  FLOOR_S1_FADE_LONG_TRAIL: {
    baseType: 'FLOOR_S1_FADE_LONG',
    direction: 'LONG',
    condition: 'unconditional — every FLOOR_S1_FADE_LONG touch (exit mechanism changes, not entry)',
    backtestScript: 'scripts/backtest_breakeven_trail.mjs',
    trailSignalName: 'B_FLOOR_S1_FADE_LONG',
    addedDate: '2026-07-21',
    monitorAtN: 20,
  },
  DAILY_OPEN_FADE_LONG_TRAIL: {
    baseType: 'DAILY_OPEN_FADE_LONG',
    direction: 'LONG',
    condition: 'unconditional — every DAILY_OPEN_FADE_LONG touch (exit mechanism changes, not entry)',
    backtestScript: 'scripts/backtest_breakeven_trail.mjs',
    trailSignalName: 'B_DAILY_OPEN_FADE_LONG',
    addedDate: '2026-07-21',
    monitorAtN: 20,
  },
  CAM_S2_FADE_LONG_TRAIL: {
    baseType: 'CAM_S2_FADE_LONG',
    direction: 'LONG',
    condition: 'unconditional — every CAM_S2_FADE_LONG touch (exit mechanism changes, not entry)',
    backtestScript: 'scripts/backtest_breakeven_trail.mjs',
    trailSignalName: 'B_CAM_S2_FADE_LONG',
    addedDate: '2026-07-21',
    monitorAtN: 20,
  },
};

/**
 * Legacy hardcoded fallback for setup_types that don't yet have a SETUP_STATUS row at all
 * (server/routes/acd.js's getShadowSetupTypes() only knows about types WITH a row --
 * a query can't distinguish "confirmed fine to show" from "never assessed"). Hides
 * brand-new/experimental types from the default Setup Log view until their first real
 * calibration run.
 *
 * PRUNED 2026-07-17: this list previously had 27 entries; querying SETUP_STATUS directly
 * showed 22 of them already had real rows (all correctly SUPPRESS/THIN_N today, so no
 * visible bug yet) -- meaning the list had quietly become 81% dead weight, AND a live
 * landmine: several of the redundant entries are THIN_N purely on small sample size with
 * positive EV (e.g. C_PAIRED_SHORT N=6 EV=+$320, A_DOWN_WEAK N=5 EV=+$208.60) -- if any
 * earns enough trades to hit PROMOTE later, this hardcoded list would keep hiding it
 * forever, the exact same staleness bug SHADOW_SETUP_TYPES was replaced for. Pruned to
 * only the 5 types confirmed to have zero SETUP_STATUS row at prune time.
 *
 * scripts/test_invariants.mjs check [6] re-verifies every entry here against live
 * SETUP_STATUS on each run and fails if one has picked up a real row -- so this can't
 * silently drift stale again the way the pruned version did. When that check fails,
 * remove the flagged entry from this Set; do not just silence the check.
 */
export const UNCALIBRATED_SHADOW_TYPES = new Set([
  'GAP_FILL_LONG', 'TRT_LONG_V2', 'TRT_SHORT_V2', 'A_UP_WEAK', 'A_DOWN_STRONG',
]);
